config: use nixos-26.05 instead of nixpkgs-unstable
It can be broken by errors like this one:

  error: nix_2_33 has been removed. use nix_2_34.

Signed-off-by: Jakub Sokołowski <jakub@status.im>